name: Workflow / Validate

on:
  push:
  pull_request:

jobs:
  validate:
    name: 👻 Validation
    uses: "frickua/actions/.github/workflows/validate.yml@main"
    permissions:
      contents: write
      issues: write
      pull-requests: write
